services:
  - type: worker
    name: anitoons-1bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: MONGODB
        sync: false
      - key: OWNER_ID
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: USER_SESSION
        sync: false
